name: Build Central Circle Remote for Windows

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/build-windows.yml"

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/windows-build-engine.yml
    with:
      upload-artifact: true
      upload-tag: "central-circle-remote-1.0.0"
